apiVersion: v1
kind: Pod
metadata:
  name: demo-web
spec:
  containers:
  - name: envtest
    image: anshuldevops/kubernetes-web:1.10.6
    ports:
    - containerPort: 8080
    env:
    - name: STRATEGY_RISK
      valueFrom:
        configMapKeyRef:
          name: simple-configmap
          key: strategy.risk 
    - name: STRATEGY_TYPE
      valueFrom:
        configMapKeyRef:
          name: simple-configmap
          key: strategy.type 